### ISSUE TITLE
Sound for cherokee syllabary app

### ISSUE THREAD

**Issue by samypaden** [mjoyner-vbservices-net/ExerciseInterleavedMaker#1]
Hello! I just downloaded the app yesterday and was working great. However today when I went to continue my lessons the sound won’t work. I have tried restarting, updating software, but so far no luck. Any suggestions? 
much appreciated!
Sam

**Comment by michael-conrad** [comment]
That's a new one.

What is your environment? (Tablet, Phone, Desktop, Laptop, Android, iOS, Linux, Windows, Mac, ...) ?

**Comment by samypaden** [comment]
I am using an iPhone SE with IOS 14.5.1 update

**Comment by samypaden** [comment]
Ah! It just started working! I have no idea what I did but super exciting! Thank you

**Comment by samypaden** [comment]
Dear Michael Conrad,
So it happened again. I’m not sure what to do. Yesterday I deleted and then reloaded the app several times and then it finally worked. after I closed it out though and reopened this morning the sound was off again 😬. Not sure if there is a button somewhere in settings that I need to push or something else in settings? I apologize I don’t have a better sense of what is going on. I really enjoy the app when the sound is on, but hard to use without it. 
Any suggestions would be great.
Thank you again!
Samuel Paden

**Comment by michael-conrad** [comment]
Hopefully things are fairing better this day.

I have not been able to recreate the issue so far.

**Comment by samypaden** [comment]
Dear Michael Conrad,
My apologies for not writing sooner, I got it figured out! It was something with my phone, it’s been working great! Thank you so much.
Hope you and yours are all well.
Kind regards,
Samuel

**Comment by michael-conrad** [comment]
np
